package com.rgapro1.ocaso;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import androidx.biometric.BiometricManager;
import androidx.biometric.BiometricPrompt;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.Text;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.File;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

public class MainActivity extends Activity {
    private static final int NAVY=Color.rgb(22,58,105), BLUE=Color.rgb(38,133,214), BG=Color.rgb(247,249,252), TEXT=Color.rgb(28,39,54), MUTED=Color.rgb(103,115,132), LINE=Color.rgb(225,230,237);
    private static final int ITER=120000, CAMERA_REQ=7101, GALLERY_REQ=7102;
    private SharedPreferences prefs; private String currentUser; private LinearLayout content; private File scanFile; private Uri scanUri;
    private final Executor biometricExecutor=Executors.newSingleThreadExecutor();
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private TextView tv(String s,float size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(16);e.setPadding(dp(14),0,dp(14),0);return e;}
    private EditText pin(String hint){EditText e=edit(hint);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);return e;}
    private GradientDrawable bg(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp((int)radius));g.setStroke(dp(1),LINE);return g;}
    private Button action(String label,boolean primary){Button b=new Button(this);b.setText(label);b.setTextSize(15);b.setAllCaps(false);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setPadding(dp(18),0,dp(14),0);b.setTextColor(primary?Color.WHITE:TEXT);b.setBackground(bg(primary?BLUE:Color.WHITE,18));return b;}

    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(NAVY);try{prefs=getSharedPreferences("rgapro_local",MODE_PRIVATE);migrate();if(hasPin())showLogin();else createUser();}catch(Exception e){safeError();}}
    private void safeError(){LinearLayout l=col();l.setGravity(Gravity.CENTER);l.setPadding(dp(28),dp(28),dp(28),dp(28));l.addView(tv("RgaPro",34,NAVY,true));l.addView(tv("No se pudo iniciar. Tus datos locales siguen guardados.",16,TEXT,false));Button b=action("Reintentar",true);b.setGravity(Gravity.CENTER);b.setOnClickListener(v->onCreate(null));l.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));setContentView(l);}
    private boolean hasPin(){return prefs.contains("pin_hash")&&prefs.contains("pin_salt");}
    private JSONObject users(){try{return new JSONObject(prefs.getString("users_json","{}"));}catch(Exception e){return new JSONObject();}}
    private void saveUsers(JSONObject u){prefs.edit().putString("users_json",u.toString()).apply();}
    private void migrate(){try{JSONObject u=users();if(u.length()==0&&hasPin()){JSONObject a=new JSONObject();a.put("pin_hash",prefs.getString("pin_hash",""));a.put("pin_salt",prefs.getString("pin_salt",""));a.put("policies",new JSONArray());a.put("biometric",true);u.put("Administrador",a);saveUsers(u);}}catch(Exception ignored){}}
    private byte[] derive(String p,byte[] salt)throws Exception{PBEKeySpec spec=new PBEKeySpec(p.toCharArray(),salt,ITER,256);try{return SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();}finally{spec.clearPassword();}}
    private boolean verify(String user,String p){try{JSONObject o=users().optJSONObject(user);if(o==null)return false;byte[] h=android.util.Base64.decode(o.optString("pin_hash"),android.util.Base64.DEFAULT);byte[] s=android.util.Base64.decode(o.optString("pin_salt"),android.util.Base64.DEFAULT);return MessageDigest.isEqual(h,derive(p,s));}catch(Exception e){return false;}}
    private void putUser(String name,String pin){try{byte[] salt=new byte[16];new SecureRandom().nextBytes(salt);JSONObject o=new JSONObject();o.put("pin_hash",android.util.Base64.encodeToString(derive(pin,salt),android.util.Base64.NO_WRAP));o.put("pin_salt",android.util.Base64.encodeToString(salt,android.util.Base64.NO_WRAP));o.put("policies",new JSONArray());o.put("biometric",true);JSONObject u=users();u.put(name,o);saveUsers(u);prefs.edit().putString("pin_hash",o.getString("pin_hash")).putString("pin_salt",o.getString("pin_salt")).apply();}catch(Exception e){throw new RuntimeException(e);}}
    private JSONObject userObject(){return users().optJSONObject(currentUser);}
    private JSONArray policies(){try{JSONObject o=userObject();JSONArray a=o==null?null:o.optJSONArray("policies");return a==null?new JSONArray():a;}catch(Exception e){return new JSONArray();}}
    private void savePolicies(JSONArray a){try{JSONObject u=users();JSONObject o=u.optJSONObject(currentUser);if(o!=null){o.put("policies",a);u.put(currentUser,o);saveUsers(u);}}catch(Exception ignored){}}

    private void logo(LinearLayout l){LinearLayout h=col();h.setGravity(Gravity.CENTER);h.setPadding(0,dp(18),0,dp(12));TextView icon=tv("◇",36,BLUE,true);icon.setGravity(Gravity.CENTER);h.addView(icon,new LinearLayout.LayoutParams(-1,dp(38)));TextView name=tv("RgaPro",30,NAVY,true);name.setGravity(Gravity.CENTER);h.addView(name);l.addView(h);}
    private void createUser(){LinearLayout l=col();l.setBackgroundColor(BG);l.setPadding(dp(24),dp(12),dp(24),dp(24));logo(l);TextView title=tv("Bienvenido a RgaPro",25,TEXT,true);title.setGravity(Gravity.CENTER);l.addView(title);TextView sub=tv("Tu gestión profesional, sencilla y segura.",16,MUTED,false);sub.setGravity(Gravity.CENTER);l.addView(sub);Space s=new Space(this);l.addView(s,new LinearLayout.LayoutParams(1,dp(18)));EditText n=edit("Nombre de usuario"),p=pin("Clave de 6 dígitos"),p2=pin("Repite la clave");l.addView(n,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(p,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(p2,new LinearLayout.LayoutParams(-1,dp(52)));Button b=action("Crear acceso seguro",true);b.setGravity(Gravity.CENTER);b.setOnClickListener(v->{String name=n.getText().toString().trim(),a=p.getText().toString(),c=p2.getText().toString();if(name.isEmpty()||!a.matches("\\d{6}")||!a.equals(c)){Toast.makeText(this,"Usa un nombre y una clave de 6 dígitos",Toast.LENGTH_LONG).show();return;}try{putUser(name,a);currentUser=name;home();}catch(Exception e){Toast.makeText(this,"No se pudo crear el acceso",Toast.LENGTH_LONG).show();}});l.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));TextView foot=tv("🔒 Los datos permanecen en este dispositivo.",13,MUTED,false);foot.setGravity(Gravity.CENTER);l.addView(foot,new LinearLayout.LayoutParams(-1,dp(48)));setContentView(l);}
    private void showLogin(){LinearLayout l=col();l.setBackgroundColor(BG);l.setPadding(dp(24),dp(12),dp(24),dp(24));logo(l);TextView title=tv("Acceso a tu cartera",24,TEXT,true);title.setGravity(Gravity.CENTER);l.addView(title);TextView sub=tv("Clave + biometría, como el ejemplo",15,MUTED,false);sub.setGravity(Gravity.CENTER);l.addView(sub);Space s=new Space(this);l.addView(s,new LinearLayout.LayoutParams(1,dp(18)));ArrayList<String> names=new ArrayList<>();Iterator<String> it=users().keys();while(it.hasNext())names.add(it.next());Collections.sort(names);if(names.isEmpty()){createUser();return;}Spinner user=new Spinner(this);user.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));l.addView(user,new LinearLayout.LayoutParams(-1,dp(52)));Button key=action("🔐  Entrar con clave",true);key.setGravity(Gravity.CENTER);key.setOnClickListener(v->login(String.valueOf(user.getSelectedItem())));l.addView(key,new LinearLayout.LayoutParams(-1,dp(54)));Button bio=action("●  Entrar con huella / biometría",false);bio.setGravity(Gravity.CENTER);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(54));bp.topMargin=dp(10);l.addView(bio,bp);bio.setOnClickListener(v->biometricLogin(String.valueOf(user.getSelectedItem())));TextView foot=tv("Tu información permanece en tu dispositivo.",13,MUTED,false);foot.setGravity(Gravity.CENTER);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(48));fp.topMargin=dp(14);l.addView(foot,fp);setContentView(l);}
    private void login(String user){EditText e=pin("Clave de 6 dígitos");AlertDialog d=new AlertDialog.Builder(this).setTitle("Entrar · "+user).setView(e).setNegativeButton("Cancelar",null).setPositiveButton("Entrar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(verify(user,e.getText().toString())){currentUser=user;d.dismiss();home();}else e.setError("Clave incorrecta");}));d.show();}

    private void biometricLogin(String user){JSONObject u=users().optJSONObject(user);if(u==null)return;if(!u.optBoolean("biometric",true)){Toast.makeText(this,"Biometría desactivada para este usuario",Toast.LENGTH_SHORT).show();return;}int result=BiometricManager.from(this).canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_WEAK);if(result!=BiometricManager.BIOMETRIC_SUCCESS){String msg=result==BiometricManager.BIOMETRIC_ERROR_NO_HARDWARE?"Este dispositivo no tiene biometría":result==BiometricManager.BIOMETRIC_ERROR_NONE_ENROLLED?"Configura primero una huella o rostro en Ajustes":"La biometría no está disponible ahora";Toast.makeText(this,msg,Toast.LENGTH_LONG).show();return;}BiometricPrompt.AuthenticationCallback cb=new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){runOnUiThread(()->{currentUser=user;home();});}@Override public void onAuthenticationError(int code,CharSequence msg){runOnUiThread(()->Toast.makeText(MainActivity.this,"Biometría: "+msg,Toast.LENGTH_SHORT).show());}};BiometricPrompt prompt=new BiometricPrompt(this,biometricExecutor,cb);BiometricPrompt.PromptInfo info=new BiometricPrompt.PromptInfo.Builder().setTitle("RgaPro").setSubtitle("Acceso seguro").setDescription("Confirma tu identidad para abrir tu cartera").setNegativeButtonText("Usar clave").setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_WEAK).build();prompt.authenticate(info);}

    private void home(){LinearLayout root=col();root.setBackgroundColor(BG);LinearLayout top=col();top.setBackgroundColor(NAVY);top.setPadding(dp(20),dp(8),dp(20),dp(16));TextView brand=tv("RgaPro",28,Color.WHITE,true);brand.setGravity(Gravity.CENTER);top.addView(brand);TextView hi=tv("Bienvenido, "+currentUser+" 👋",18,Color.WHITE,false);hi.setGravity(Gravity.CENTER);top.addView(hi);root.addView(top);ScrollView sc=new ScrollView(this);LinearLayout body=col();body.setPadding(dp(18),dp(18),dp(18),dp(22));TextView welcome=tv("¿Qué quieres hacer hoy?\nTu cartera, tus clientes y tus documentos en un solo lugar.",20,TEXT,true);welcome.setPadding(dp(8),dp(4),dp(8),dp(18));body.addView(welcome);addMenu(body,"👤","Tus datos y clientes","Buscar por nombre, DNI, teléfono, email o póliza",v->clients());addMenu(body,"▣","Pólizas","Vida · hogar · auto · salud · decesos · otras",v->policiesPage());addMenu(body,"▤","Documentos","Escanear y leer datos automáticamente con OCR",v->scanDocument());addMenu(body,"🔔","Vencimientos","Avisos a 60 · 45 · 30 · 15 días",v->expiries());addMenu(body,"🔒","Seguridad","Clave, biometría y control de compartición",v->security());TextView foot=tv("RgaPro V1.4 · Gestión profesional",13,MUTED,false);foot.setGravity(Gravity.CENTER);body.addView(foot,new LinearLayout.LayoutParams(-1,dp(48)));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Button out=action("Cerrar sesión",false);out.setGravity(Gravity.CENTER);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(50));op.setMargins(dp(18),0,dp(18),dp(14));root.addView(out,op);out.setOnClickListener(v->{currentUser=null;showLogin();});setContentView(root);}
    private void addMenu(LinearLayout body,String icon,String title,String sub,View.OnClickListener click){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(14),dp(8),dp(10),dp(8));card.setBackground(bg(Color.WHITE,18));TextView i=tv(icon,28,BLUE,true);i.setGravity(Gravity.CENTER);card.addView(i,new LinearLayout.LayoutParams(dp(50),dp(66)));LinearLayout words=col();words.setPadding(dp(8),0,0,0);words.addView(tv(title,18,TEXT,true));words.addView(tv(sub,13,MUTED,false));card.addView(words,new LinearLayout.LayoutParams(0,dp(66),1));TextView arrow=tv("›",30,MUTED,false);arrow.setGravity(Gravity.CENTER);card.addView(arrow,new LinearLayout.LayoutParams(dp(26),dp(66)));card.setOnClickListener(click);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(88));cp.bottomMargin=dp(10);body.addView(card,cp);}
    private void page(String title,String subtitle){LinearLayout root=col();root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(8),dp(8),dp(18),dp(8));head.setBackgroundColor(NAVY);Button back=action("‹",false);back.setTextColor(Color.WHITE);back.setBackgroundColor(Color.TRANSPARENT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->home());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout h=col();h.addView(tv(title,20,Color.WHITE,true));h.addView(tv(subtitle,12,Color.WHITE,false));head.addView(h);root.addView(head);content=col();content.setPadding(dp(16),dp(16),dp(16),dp(20));ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private void clients(){page("Tus clientes","Busca por cualquier dato");EditText q=edit("Nombre, DNI, teléfono, email, póliza...");q.setBackground(bg(Color.WHITE,16));content.addView(q,new LinearLayout.LayoutParams(-1,dp(54)));LinearLayout list=col();content.addView(list);Runnable render=()->{list.removeAllViews();JSONArray a=policies();for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p!=null&&matches(p,q.getText().toString())){Button b=action("👤  "+p.optString("holder","Sin titular")+"\n      "+p.optString("type","Otros")+" · "+p.optString("number",""),false);b.setOnClickListener(v->detail(p));list.addView(b,new LinearLayout.LayoutParams(-1,dp(74)));}}};q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render.run();}public void afterTextChanged(android.text.Editable e){}});render.run();}
    private boolean matches(JSONObject p,String q){if(q==null||q.trim().isEmpty())return true;String n=q.toLowerCase(Locale.ROOT);for(String k:new String[]{"holder","holderDni","phone","email","address","type","number","expiry","ocrText","members"})if(p.optString(k).toLowerCase(Locale.ROOT).contains(n))return true;return false;}
    private void detail(JSONObject p){StringBuilder m=new StringBuilder();m.append("Titular: ").append(p.optString("holder","—"));m.append("\nDNI/NIE: ").append(p.optString("holderDni","—"));m.append("\nTeléfono: ").append(p.optString("phone","—"));m.append("\nEmail: ").append(p.optString("email","—"));m.append("\nTipo: ").append(p.optString("type","—"));m.append("\nPóliza: ").append(p.optString("number","—"));m.append("\nVencimiento: ").append(p.optString("expiry","—"));JSONArray mem=p.optJSONArray("members");if(mem!=null&&mem.length()>0){m.append("\n\nPersonas incluidas:");for(int i=0;i<mem.length();i++){JSONObject x=mem.optJSONObject(i);if(x!=null)m.append("\n• ").append(x.optString("name","—")).append(" · ").append(x.optString("dni","—"));}}new AlertDialog.Builder(this).setTitle("Ficha de cliente").setMessage(m.toString()).setPositiveButton("Cerrar",null).show();}

    private void policiesPage(){page("Pólizas","Separadas por tipo");String[] types={"Todas","Auto","Hogar","Vida","Salud","Decesos","Otros"};Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,types));content.addView(sp,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout list=col();content.addView(list);Runnable render=()->{list.removeAllViews();String filter=String.valueOf(sp.getSelectedItem());JSONArray a=policies();for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p!=null&&(filter.equals("Todas")||filter.equalsIgnoreCase(p.optString("type","Otros")))){Button b=action(p.optString("type","Otros")+" · "+p.optString("holder","Sin titular")+"\nPóliza "+p.optString("number","—")+" · vence "+p.optString("expiry","—"),false);b.setOnClickListener(v->detail(p));list.addView(b,new LinearLayout.LayoutParams(-1,dp(76)));}}};sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){render.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});render.run();}
    private void expiries(){page("Próximos vencimientos","60 · 45 · 30 · 15 días");JSONArray a=policies();SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ROOT);Date now=new Date();boolean any=false;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;try{Date d=f.parse(p.optString("expiry"));long days=(d.getTime()-now.getTime())/(24L*60*60*1000);if(days>=0&&days<=60){any=true;TextView t=tv(p.optString("holder","Sin titular")+"\n"+p.optString("type","Otros")+" · "+days+" días · "+p.optString("expiry"),17,TEXT,true);t.setPadding(dp(16),dp(14),dp(16),dp(14));t.setBackground(bg(Color.WHITE,16));content.addView(t,new LinearLayout.LayoutParams(-1,dp(76)));}}catch(Exception ignored){}}if(!any)content.addView(tv("No hay pólizas que venzan en los próximos 60 días.",16,MUTED,false));}

    private void security(){page("Seguridad y privacidad","El control es tuyo");JSONObject u=userObject();Switch bio=new Switch(this);bio.setText("Permitir acceso biométrico");bio.setTextSize(17);bio.setTextColor(TEXT);bio.setChecked(u==null||u.optBoolean("biometric",true));content.addView(bio,new LinearLayout.LayoutParams(-1,dp(58)));bio.setOnCheckedChangeListener((b,c)->{try{JSONObject all=users();JSONObject x=all.optJSONObject(currentUser);x.put("biometric",c);all.put(currentUser,x);saveUsers(all);}catch(Exception ignored){}});Button test=action("●  Probar biometría ahora",false);test.setGravity(Gravity.CENTER);content.addView(test,new LinearLayout.LayoutParams(-1,dp(54)));test.setOnClickListener(v->biometricLogin(currentUser));Button share=action("Compartir datos almacenados…",false);share.setGravity(Gravity.CENTER);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(54));sp.topMargin=dp(10);content.addView(share,sp);share.setOnClickListener(v->shareData());content.addView(tv("Compartir solo se realiza cuando tú lo eliges. No se envían datos automáticamente.",13,MUTED,false));}
    private void shareData(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,"RgaPro: compartición iniciada por el usuario.");startActivity(Intent.createChooser(i,"Compartir"));}

    private void scanDocument(){page("Escanear documento","Fotografía → OCR → datos → cliente");TextView info=tv("Coloca el documento completo, bien iluminado y sin reflejos.\nRgaPro leerá el texto en el dispositivo y te mostrará los campos antes de guardarlos.",15,MUTED,false);info.setPadding(dp(6),dp(6),dp(6),dp(16));content.addView(info);Button camera=action("📷  Escanear con cámara",true);camera.setGravity(Gravity.CENTER);content.addView(camera,new LinearLayout.LayoutParams(-1,dp(58)));camera.setOnClickListener(v->openCamera());Button gallery=action("▣  Elegir una foto existente",false);gallery.setGravity(Gravity.CENTER);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(54));gp.topMargin=dp(10);content.addView(gallery,gp);gallery.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType("image/*");startActivityForResult(i,GALLERY_REQ);});}
    private void openCamera(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA_REQ);return;}try{File dir=new File(getCacheDir(),"scans");if(!dir.exists())dir.mkdirs();scanFile=File.createTempFile("rgapro_",".jpg",dir);scanUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",scanFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,scanUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,CAMERA_REQ);}catch(Exception e){Toast.makeText(this,"No se pudo abrir la cámara",Toast.LENGTH_LONG).show();}}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==CAMERA_REQ&&results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)openCamera();}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK)return;Uri uri=null;if(request==CAMERA_REQ)uri=scanUri;else if(request==GALLERY_REQ&&data!=null)uri=data.getData();if(uri!=null)runOcr(uri);}
    private void runOcr(Uri uri){try{InputImage image=InputImage.fromFilePath(this,uri);TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);Toast.makeText(this,"Leyendo documento…",Toast.LENGTH_SHORT).show();recognizer.process(image).addOnSuccessListener(text->{showOcrResult(text.getText());recognizer.close();}).addOnFailureListener(e->{recognizer.close();Toast.makeText(this,"No se pudo leer el documento. Haz otra foto con más luz.",Toast.LENGTH_LONG).show();});}catch(Exception e){Toast.makeText(this,"No se pudo preparar el documento",Toast.LENGTH_LONG).show();}}
    private void showOcrResult(String raw){String dni=extract(raw,"\\b(?:[XYZ]?[0-9]{7}[A-Z]|[0-9]{8}[A-Z])\\b",0);String phone=extract(raw,"(?:\\+34\\s?)?[6789][0-9]{8}",0);String email=extract(raw,"[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}",Pattern.CASE_INSENSITIVE);String date=extract(raw,"\\b(?:0?[1-9]|[12][0-9]|3[01])[/.-](?:0?[1-9]|1[0-2])[/.-](?:19|20)\\d{2}\\b",0);String name=guessName(raw);LinearLayout box=col();box.setPadding(dp(6),0,dp(6),0);EditText n=edit("Nombre / titular");n.setText(name);EditText d=edit("DNI / NIE");d.setText(dni);EditText ph=edit("Teléfono");ph.setText(phone);EditText em=edit("Email");em.setText(email);EditText ex=edit("Vencimiento (dd/MM/yyyy)");ex.setText(normalizeDate(date));Spinner type=new Spinner(this);String[] types={"Auto","Hogar","Vida","Salud","Decesos","Otros"};type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,types));box.addView(n);box.addView(d);box.addView(ph);box.addView(em);box.addView(ex);box.addView(type);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Datos detectados por OCR").setView(box).setNegativeButton("Descartar",null).setNeutralButton("Buscar cliente",null).setPositiveButton("Guardar cliente",null).create();dialog.setOnShowListener(x->{dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{clientsWithQuery(d.getText().toString().trim().isEmpty()?n.getText().toString().trim():d.getText().toString().trim());dialog.dismiss();});dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{saveOcrClient(n.getText().toString(),d.getText().toString(),ph.getText().toString(),em.getText().toString(),ex.getText().toString(),String.valueOf(type.getSelectedItem()),raw);dialog.dismiss();});});dialog.show();}
    private String extract(String text,String regex,int flags){Matcher m=Pattern.compile(regex,flags).matcher(text.replace("\n"," "));return m.find()?m.group():"";}
    private String guessName(String raw){String[] lines=raw.split("\\r?\\n");for(String line:lines){String u=line.trim();if(u.toUpperCase(Locale.ROOT).contains("NOMBRE")||u.toUpperCase(Locale.ROOT).contains("TITULAR")){String s=u.replaceFirst("(?i).*?(NOMBRE|TITULAR)[:\\s-]*"," ").trim();if(s.length()>3)return s;}}for(String line:lines){String s=line.trim();if(s.length()>6&&s.length()<60&&s.matches("[A-Za-zÁÉÍÓÚÜÑáéíóúüñ .'-]+"))return s;}return "";}
    private String normalizeDate(String s){return s.replace('.', '/').replace('-', '/');}
    private void saveOcrClient(String name,String dni,String phone,String email,String expiry,String type,String raw){try{JSONArray a=policies();JSONObject p=new JSONObject();p.put("holder",name.trim());p.put("holderDni",dni.trim().toUpperCase(Locale.ROOT));p.put("phone",phone.trim());p.put("email",email.trim());p.put("expiry",expiry.trim());p.put("type",type);p.put("number","");p.put("ocrText",raw);p.put("members",new JSONArray());a.put(p);savePolicies(a);Toast.makeText(this,"Cliente guardado. Ya aparece en Clientes.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"No se pudo guardar el cliente",Toast.LENGTH_LONG).show();}}
    private void clientsWithQuery(String q){clients();if(content!=null&&content.getChildCount()>0&&content.getChildAt(0) instanceof EditText)((EditText)content.getChildAt(0)).setText(q);}

    @Override protected void onDestroy(){super.onDestroy();}
}
