package com.rgapro1.ocaso;

import android.Manifest;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import androidx.biometric.BiometricManager;
import androidx.biometric.BiometricPrompt;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import androidx.fragment.app.FragmentActivity;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.util.*;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;

public class MainActivity extends FragmentActivity {
    private static final int NAVY=Color.rgb(12,35,67), BLUE=Color.rgb(25,133,224), BG=Color.rgb(247,249,252), TEXT=Color.rgb(28,39,54), MUTED=Color.rgb(103,115,132), LINE=Color.rgb(225,230,237);
    private static final int CAMERA_REQ=7101, IMAGE_REQ=7102, PDF_REQ=7103;
    private SharedPreferences prefs; private String currentUser; private LinearLayout content;
    private File scanFile; private Uri scanUri; private boolean dniMode=false; private int dniSide=0; private boolean multiMode=false;
    private final ArrayList<String> sessionPaths=new ArrayList<>(); private final ArrayList<String> sessionTexts=new ArrayList<>();
    private final Executor biometricExecutor=Executors.newSingleThreadExecutor();
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private TextView tv(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(b?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);v.setPadding(dp(6),dp(6),dp(6),dp(6));return v;}
    private EditText edit(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setTextSize(16);e.setPadding(dp(14),0,dp(14),0);return e;}
    private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),LINE);return g;}
    private Button action(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:TEXT);b.setBackground(bg(primary?BLUE:Color.WHITE,18));return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);prefs=getSharedPreferences("rgapro_local",MODE_PRIVATE);if(!prefs.contains("user"))createUser();else showLogin();}
    private void createUser(){LinearLayout l=col();l.setBackgroundColor(BG);l.setPadding(dp(24),dp(20),dp(24),dp(24));l.setGravity(Gravity.CENTER_HORIZONTAL);l.addView(tv("RgaPro",32,NAVY,true));l.addView(tv("Bienvenido · acceso seguro",22,TEXT,true));EditText u=edit("Usuario"),p=edit("Clave de 6 dígitos"),p2=edit("Repite la clave");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);p2.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);l.addView(u,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(p,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(p2,new LinearLayout.LayoutParams(-1,dp(52)));Button go=action("Crear acceso",true);l.addView(go,new LinearLayout.LayoutParams(-1,dp(56)));go.setOnClickListener(v->{if(u.getText().toString().trim().isEmpty()||!p.getText().toString().matches("\\d{6}")||!p.getText().toString().equals(p2.getText().toString())){Toast.makeText(this,"Usa una clave de 6 dígitos y repítela",Toast.LENGTH_LONG).show();return;}prefs.edit().putString("user",u.getText().toString().trim()).putString("pin",p.getText().toString()).putBoolean("biometric",true).apply();currentUser=u.getText().toString().trim();home();});l.addView(tv("🔒 Los datos se mantienen en el dispositivo.",13,MUTED,false));setContentView(l);}
    private void showLogin(){LinearLayout l=col();l.setBackgroundColor(NAVY);l.setPadding(dp(24),dp(20),dp(24),dp(24));l.setGravity(Gravity.CENTER_HORIZONTAL);l.addView(tv("RgaPro",32,Color.WHITE,true));l.addView(tv("Acceso seguro",22,Color.WHITE,true));l.addView(tv("Introduce tu usuario y clave o usa biometría",15,Color.WHITE,false));EditText u=edit("Usuario"),p=edit("PIN de 6 dígitos");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);l.addView(u,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(p,new LinearLayout.LayoutParams(-1,dp(52)));Button key=action("🔐 Entrar",true),bio=action("● Entrar con huella / biometría",false),newU=action("＋ Nuevo usuario",false),reset=action("♻ Reiniciar seguridad",false);l.addView(key,new LinearLayout.LayoutParams(-1,dp(56)));l.addView(bio,new LinearLayout.LayoutParams(-1,dp(56)));l.addView(newU,new LinearLayout.LayoutParams(-1,dp(50)));l.addView(reset,new LinearLayout.LayoutParams(-1,dp(50)));key.setOnClickListener(v->{if(prefs.getString("user","").equals(u.getText().toString().trim())&&prefs.getString("pin","").equals(p.getText().toString())){currentUser=prefs.getString("user","");home();}else Toast.makeText(this,"Usuario o PIN incorrectos.",Toast.LENGTH_LONG).show();});bio.setOnClickListener(v->biometricLogin());newU.setOnClickListener(v->createUser());reset.setOnClickListener(v->{prefs.edit().remove("user").remove("pin").remove("biometric").apply();createUser();});setContentView(l);}
    private void biometricLogin(){if(!prefs.getBoolean("biometric",true)){Toast.makeText(this,"Biometría desactivada",Toast.LENGTH_SHORT).show();return;}int r=BiometricManager.from(this).canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_WEAK);if(r!=BiometricManager.BIOMETRIC_SUCCESS){Toast.makeText(this,"Biometría no disponible. Usa tu PIN.",Toast.LENGTH_LONG).show();return;}BiometricPrompt p=new BiometricPrompt(this,biometricExecutor,new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){runOnUiThread(()->{currentUser=prefs.getString("user","");home();});}});p.authenticate(new BiometricPrompt.PromptInfo.Builder().setTitle("RgaPro").setSubtitle("Acceso seguro").setNegativeButtonText("Usar PIN").setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_WEAK).build());}
    private void home(){LinearLayout r=col();r.setBackgroundColor(BG);TextView h=tv("RgaPro\nClientes, pólizas y documentos\nUsuario: "+currentUser,24,NAVY,true);r.addView(h);Button scan=action("📄 Escanear / OCR",true);r.addView(scan,new LinearLayout.LayoutParams(-1,dp(58)));scan.setOnClickListener(v->scanDocument());Button out=action("Cerrar sesión",false);r.addView(out,new LinearLayout.LayoutParams(-1,dp(50)));out.setOnClickListener(v->showLogin());setContentView(r);}
    private void page(String title,String sub){LinearLayout r=col();r.setBackgroundColor(BG);r.addView(tv(title,24,NAVY,true));r.addView(tv(sub,14,MUTED,false));content=col();ScrollView s=new ScrollView(this);s.addView(content);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button back=action("← Volver",false);back.setOnClickListener(v->home());r.addView(back,new LinearLayout.LayoutParams(-1,dp(48)));setContentView(r);}
    private void scanDocument(){page("OCR de documentos","Selecciona qué quieres leer");content.addView(tv("Solo dos opciones. DNI/NIE funciona exclusivamente con cámara y doble cara. Documentos admite cámara multipágina y archivos PDF/JPEG.",15,TEXT,false));Button dni=action("🪪 DNI / NIE\nAnverso + reverso",true);content.addView(dni,new LinearLayout.LayoutParams(-1,dp(76)));dni.setOnClickListener(v->{resetSession();dniMode=true;multiMode=false;openCamera();});Button docs=action("📄 DOCUMENTOS\nCámara · PDF · JPEG",false);content.addView(docs,new LinearLayout.LayoutParams(-1,dp(76)));docs.setOnClickListener(v->documentsMenu());}
    private void documentsMenu(){page("Documentos","Captura o carga y deja que RgaPro clasifique");Button cam=action("📷 Cámara para documentos\n1 o varias páginas",true);content.addView(cam,new LinearLayout.LayoutParams(-1,dp(74)));cam.setOnClickListener(v->{resetSession();dniMode=false;multiMode=true;openCamera();});Button files=action("📁 JPEG / PDF\nLeer y clasificar en Póliza o DNI/NIE",false);content.addView(files,new LinearLayout.LayoutParams(-1,dp(74)));files.setOnClickListener(v->{resetSession();pickFiles();});content.addView(tv("El documento se conserva y la información relevante se propone para guardarla en el cliente correcto.",14,MUTED,false));}
    private void resetSession(){sessionPaths.clear();sessionTexts.clear();dniSide=0;}
    private void openCamera(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA_REQ);return;}try{File d=new File(getCacheDir(),"scans");if(!d.exists())d.mkdirs();scanFile=File.createTempFile("rgapro_",".jpg",d);scanUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",scanFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,scanUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,CAMERA_REQ);}catch(Exception e){Toast.makeText(this,"No se pudo abrir la cámara",Toast.LENGTH_LONG).show();}}
    private void pickFiles(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/jpeg","image/jpg","application/pdf"});i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMAGE_REQ);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK)return;try{if(request==CAMERA_REQ){String path=copyFileToSession(scanFile);if(path==null)throw new IOException("No se pudo guardar la foto");sessionPaths.add(path);if(dniMode){if(dniSide==0){dniSide=1;processLastImage(true);}else processLastImage(false);}else{processLastImage(false);}}else if(request==IMAGE_REQ&&data!=null){if(data.getClipData()!=null){ClipData c=data.getClipData();for(int i=0;i<c.getItemCount();i++){String p=copyUriToSession(c.getItemAt(i).getUri(),guessExt(c.getItemAt(i).getUri()));if(p!=null)sessionPaths.add(p);}}else if(data.getData()!=null){String p=copyUriToSession(data.getData(),guessExt(data.getData()));if(p!=null)sessionPaths.add(p);}processSelectedFiles();}}catch(Exception e){Toast.makeText(this,"No se pudo procesar: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private String guessExt(Uri u){String t=getContentResolver().getType(u);return t!=null&&t.toLowerCase(Locale.ROOT).contains("pdf")?"pdf":"jpg";}
    private void processSelectedFiles(){if(sessionPaths.isEmpty())return;String ext=sessionPaths.get(0).toLowerCase(Locale.ROOT);if(ext.endsWith(".pdf")){Uri u=Uri.parse(sessionPaths.get(0));PdfOcrHelper.process(this,u,new PdfOcrHelper.Callback(){public void onSuccess(String text){runOnUiThread(()->showOcrResult(text));}public void onError(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"No se pudo leer el PDF.",Toast.LENGTH_LONG).show());}});}else processAllImages(0,new StringBuilder());}
    private void processLastImage(boolean askBack){processImageFile(sessionPaths.get(sessionPaths.size()-1),new ImageCallback(){public void ok(String text){sessionTexts.add(text);if(askBack){new AlertDialog.Builder(MainActivity.this).setTitle("Anverso leído").setMessage("Ahora fotografía el REVERSO del DNI/NIE.").setNegativeButton("Cancelar",null).setPositiveButton("Fotografiar reverso",(d,w)->openCamera()).show();}else if(dniMode){showOcrResult(joinTexts());}else askMorePages();}public void error(Exception e){Toast.makeText(MainActivity.this,"No se pudo leer la foto: "+e.getMessage(),Toast.LENGTH_LONG).show();}});}
    private void askMorePages(){new AlertDialog.Builder(this).setTitle("Página procesada").setMessage("Puedes añadir otra página o finalizar.").setNegativeButton("Finalizar",(d,w)->showOcrResult(joinTexts())).setPositiveButton("Añadir otra página",(d,w)->openCamera()).show();}
    private String joinTexts(){StringBuilder s=new StringBuilder();for(int i=0;i<sessionTexts.size();i++)s.append("\n--- DOCUMENTO ").append(i+1).append(" ---\n").append(sessionTexts.get(i)).append('\n');return s.toString();}
    private void processAllImages(int index,StringBuilder all){if(index>=sessionPaths.size()){showOcrResult(all.toString());return;}processImageFile(sessionPaths.get(index),new ImageCallback(){public void ok(String text){sessionTexts.add(text);all.append("\n--- IMAGEN ").append(index+1).append(" ---\n").append(text).append('\n');processAllImages(index+1,all);}public void error(Exception e){processAllImages(index+1,all);}});}
    private interface ImageCallback{void ok(String text);void error(Exception e);}
    private void processImageFile(String path,ImageCallback cb){new Thread(()->{try{BitmapFactory.Options o=new BitmapFactory.Options();o.inSampleSize=2;Bitmap bm=BitmapFactory.decodeFile(path,o);if(bm==null)throw new IOException("Imagen no válida");InputImage image=InputImage.fromBitmap(bm,0);TextRecognizer rec=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);rec.process(image).addOnSuccessListener(r->{String text=r.getText();bm.recycle();rec.close();cb.ok(text);}).addOnFailureListener(e->{bm.recycle();rec.close();cb.error(e);});}catch(Exception e){cb.error(e);}}).start();}
    private String copyFileToSession(File source)throws IOException{File dir=new File(getFilesDir(),"documents");if(!dir.exists())dir.mkdirs();File out=new File(dir,"scan_"+System.currentTimeMillis()+".jpg");copy(source,out);return out.getAbsolutePath();}
    private String copyUriToSession(Uri uri,String ext){try{File dir=new File(getFilesDir(),"documents");if(!dir.exists())dir.mkdirs();File out=new File(dir,"doc_"+System.currentTimeMillis()+"."+ext);InputStream in=getContentResolver().openInputStream(uri);if(in==null)return null;FileOutputStream os=new FileOutputStream(out);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)os.write(buf,0,n);in.close();os.close();return out.getAbsolutePath();}catch(Exception e){return null;}}
    private void copy(File a,File b)throws IOException{FileInputStream in=new FileInputStream(a);FileOutputStream out=new FileOutputStream(b);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.close();}
    private String cleanText(String s){return s==null?"":s.trim().replaceAll("\\s+"," ");}
    private void showOcrResult(String raw){String up=raw==null?"":raw.toUpperCase(Locale.ROOT);boolean looksDni=up.contains("DNI")||up.contains("NIE")||up.contains("IDESP")||up.matches("(?s).*\\b[XYZ]?[0-9]{7}[A-Z]\\b.*");boolean looksPolicy=up.contains("PÓLIZA")||up.contains("POLIZA")||up.contains("TOMADOR")||up.contains("ASEGURADO")||up.contains("FECHA DE EFECTO")||up.contains("CONDICIONES PARTICULARES");String classification=looksDni?"DNI/NIE":looksPolicy?"Póliza":"Documento";LinearLayout b=col();b.addView(tv("Documento identificado como: "+classification,18,TEXT,true));b.addView(tv("Revisa los datos antes de guardar.\n\n"+cleanText(raw),14,MUTED,false));Button save=action("💾 Guardar en cliente correcto",true);b.addView(save,new LinearLayout.LayoutParams(-1,dp(58)));save.setOnClickListener(v->Toast.makeText(this,"Resultado leído. Revisión y guardado en cliente disponibles.",Toast.LENGTH_LONG).show());setContentView(b);}
}
