package com.rgapro1.ocaso;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Matrix;
import android.net.Uri;
import android.os.Bundle;
import android.os.ParcelFileDescriptor;
import android.provider.MediaStore;
import android.util.Base64;
import android.view.ViewGroup;
import android.webkit.JavascriptInterface;
import android.webkit.ValueCallback;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import androidx.exifinterface.media.ExifInterface;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RgaProActivity extends Activity {
    private static final int PICK=8101,CAMERA=8102;
    private WebView web; private TextRecognizer recognizer; private File cameraFile; private String cameraSide="front";
    private ValueCallback<Uri[]> pendingFileCallback; private File pendingFrontFile,pendingReverseFile; private final List<Uri> pendingUris=new ArrayList<>();
    private String frontRaw="",reverseRaw=""; private JSONObject frontParsed=new JSONObject(),reverseParsed=new JSONObject();

    @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web,new ViewGroup.LayoutParams(-1,-1));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){applyCleanUi(v);}});web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(pendingFileCallback!=null)pendingFileCallback.onReceiveValue(null);pendingFileCallback=cb;pickDocument();return true;}});web.addJavascriptInterface(new Bridge(),"RgaProCamera");recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);web.loadUrl("file:///android_asset/prototype/index.html");}

    private void applyCleanUi(WebView v){String js="(function(){"
      +"var p=document.getElementById('n-policies');if(p)p.remove();document.querySelectorAll('.nav button').forEach(function(b){if((b.textContent||'').trim().toLowerCase()==='pólizas')b.remove();});"
      +"var g=document.querySelector('#home .grid');if(g)g.style.display='none';['ocrTypeDni','ocrTypeDoc','ocrTypePol'].forEach(function(id){var x=document.getElementById(id);if(x)x.style.display='none';});"
      +"var e=document.querySelector('#ocr .eyebrow');if(e)e.style.display='none';var st=document.getElementById('step');if(st)st.style.display='block';"
      +"var o=document.querySelector('#ocr .ocrbox');if(o){o.querySelectorAll('button').forEach(function(b){b.style.display='none';});"
      +"var a=document.createElement('button');a.id='ocrAdd';a.className='primary full';a.textContent='📷 Añadir documento';a.onclick=function(){RgaProCamera.chooseInput();};"
      +"var pr=document.createElement('button');pr.id='ocrProcess';pr.className='primary full';pr.textContent='▶️ Procesar documento';pr.style.marginTop='8px';pr.disabled=true;pr.onclick=function(){RgaProCamera.processPending();};"
      +"var rv=document.createElement('button');rv.id='ocrReverse';rv.className='secondary full';rv.textContent='↩️ Añadir reverso del DNI/NIE';rv.style.marginTop='8px';rv.style.display='none';rv.onclick=function(){RgaProCamera.captureReverse();};"
      +"var ch=document.createElement('button');ch.id='ocrChange';ch.className='ghost full';ch.textContent='🗑️ Cambiar documento';ch.style.marginTop='8px';ch.onclick=function(){RgaProCamera.clearPending();};o.appendChild(a);o.appendChild(pr);o.appendChild(rv);o.appendChild(ch);}"
      +"var f=document.getElementById('ocrFields');"
      +"window.setOcrResult=function(data){try{var d=typeof data==='string'?JSON.parse(data):data;"
      +"if(d.preview){var box=document.getElementById('ocrPreviewList');if(!box){box=document.createElement('div');box.id='ocrPreviewList';box.className='list';var ob=document.querySelector('#ocr .ocrbox');ob.insertBefore(box,ob.firstChild);}var id='pv_'+(d.side||'document');var old=document.getElementById(id);if(old)old.remove();var w=document.createElement('div');w.id=id;w.className='field';w.innerHTML='<div class=\\\"fieldhead\\\"><label>'+(d.side==='front'?'ANVERSO':d.side==='reverse'?'REVERSO':'DOCUMENTO')+'</label></div><img src=\\\"data:image/jpeg;base64,'+d.preview+'\\\" class=\\\"docimg\\\" style=\\\"max-height:360px;object-fit:contain;margin-top:8px\\\"><div class=\\\"small\\\" style=\\\"margin-top:6px\\\">Vista previa. Todavía no se ha guardado.</div>';box.appendChild(w);}"
      +"if(d.previewOnly){var pp=document.getElementById('ocrProcess');if(pp)pp.disabled=false;var cs=document.getElementById('ocrStatus');if(cs)cs.textContent='Vista previa. Comprueba que es el documento correcto y pulsa Procesar documento.';return;}"
      +"var front=d.side==='front',rev=d.side==='reverse';if(front)window.__rgaFront=d;if(rev)window.__rgaReverse=d;window.__rgaOcrType=d.classification==='DNI/NIE'?'DNI':(d.classification==='Póliza'?'POLIZA':'DOCUMENTO');ocrType=window.__rgaOcrType;"
      +"var src=window.__rgaFront||d,rr=window.__rgaReverse,val=function(k){return(src[k]||'')||((rr&&rr[k])||'')};var dni=val('documentNumber'),name=val('name'),sur=val('surname'),bd=val('birthDate');"
      +"function date(v){if(!v)return '';var x=String(v).trim().replace(/\\./g,'/').replace(/-/g,'/');var m=x.match(/^(\\d{1,2})[\\/](\\d{1,2})[\\/](\\d{4})$/);if(m)return('0'+m[1]).slice(-2)+'/'+('0'+m[2]).slice(-2)+'/'+m[3];var n=x.replace(/\\D/g,'');if(n.length===8){var dd=n.slice(0,2),mm=n.slice(2,4),yy=n.slice(4);if(+dd<=31&&+mm<=12)return dd+'/'+mm+'/'+yy;}return v;}"
      +"var isDni=window.__rgaOcrType==='DNI',status=document.getElementById('ocrStatus');if(status)status.textContent=rev?'✓ Anverso y reverso procesados. Revisa los datos y guarda.':(front&&isDni?'✓ Anverso procesado. Ahora añade el REVERSO del DNI/NIE.':'OCR procesado. Revisa los datos y guarda.');"
      +"var rvb=document.getElementById('ocrReverse');if(rvb)rvb.style.display=(front&&isDni&&!rr)?'block':'none';var proc=document.getElementById('ocrProcess');if(proc)proc.style.display='block';var change=document.getElementById('ocrChange');if(change)change.style.display='block';"
      +"var fields=isDni?[['documentNumber','Nº DNI/NIE',dni],['name','Nombre',name],['surname','Apellidos',sur],['birthDate','Fecha de nacimiento',date(bd)]]:[['policyNumber','Nº póliza',val('policyNumber')],['policyType','Tipo de póliza',val('policyType')],['policyExpiry','Vencimiento',val('policyExpiry')],['name','Tomador / titular',name],['surname','Apellidos',sur],['phone','Teléfono',val('phone')],['address','Dirección',val('address')],['email','Email',val('email')]];"
      +"f.innerHTML=fields.map(function(x){return'<div class=\\\"field\\\"><div class=\\\"fieldhead\\\"><label>'+x[1]+'</label><span class=\\\"pill warn\\\">Revisión</span></div><input id=\\\"ocr_'+x[0]+'\\\" value=\\\"'+(x[2]||'').replace(/\\\"/g,'&quot;')+'\\\" readonly></div>';}).join('');"
      +"}catch(e){console.log(e);}};window.__rgaOcrType='DNI';"
      +"window.clearOcrUi=function(){window.__rgaFront=null;window.__rgaReverse=null;window.__rgaOcrType='DNI';ocrType='DNI';var b=document.getElementById('ocrPreviewList');if(b)b.remove();var f=document.getElementById('ocrFields');if(f)f.innerHTML='';var st=document.getElementById('ocrStatus');if(st)st.textContent='Añade un documento y comprueba la vista previa antes de procesarlo.';var rv=document.getElementById('ocrReverse');if(rv)rv.style.display='none';var pp=document.getElementById('ocrProcess');if(pp)pp.disabled=true;};"
      +"window.__rgaOriginalSaveOcr=window.saveOcr;window.saveOcr=function(){if(window.__rgaOcrType==='DNI'&&window.__rgaFront&&!window.__rgaReverse){alert('Para un DNI/NIE debes procesar también el reverso antes de guardar.');return;}if(window.__rgaOriginalSaveOcr)window.__rgaOriginalSaveOcr();};})();";v.evaluateJavascript(js,null);}

    private class Bridge{@JavascriptInterface public void chooseInput(){runOnUiThread(()->{clearPending();showInputChooser();});}@JavascriptInterface public void capture(String side){runOnUiThread(()->startCamera(side));}@JavascriptInterface public void captureReverse(){runOnUiThread(()->startCamera("reverse"));}@JavascriptInterface public void processPending(){runOnUiThread(RgaProActivity.this::processPending);}@JavascriptInterface public void clearPending(){runOnUiThread(RgaProActivity.this::clearPending);}@JavascriptInterface public void pickPdf(){runOnUiThread(RgaProActivity.this::pickDocument);}}
    private void showInputChooser(){new AlertDialog.Builder(this).setTitle("Añadir documento").setItems(new String[]{"📷 Cámara","📁 Archivos / PDF"},(d,w)->{if(w==0)startCamera("front");else pickDocument();}).show();}
    private void pickDocument(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK);}
    private void startCamera(String side){cameraSide=side==null?"front":side;if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA);return;}try{File dir=new File(getCacheDir(),"rgapro_scan");if(!dir.exists())dir.mkdirs();cameraFile=File.createTempFile("rgapro_",".jpg",dir);Uri out=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",cameraFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,out);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,CAMERA);}catch(Exception e){showError("No se pudo abrir la cámara");}}
    @Override protected void onActivityResult(int r,int res,Intent d){super.onActivityResult(r,res,d);if(r==CAMERA){if(res==RESULT_OK&&cameraFile!=null){if("reverse".equals(cameraSide))pendingReverseFile=cameraFile;else pendingFrontFile=cameraFile;showPendingPreview(cameraFile,"reverse".equals(cameraSide)?"reverse":"front");}return;}if(r!=PICK)return;if(res!=RESULT_OK||d==null){if(pendingFileCallback!=null){pendingFileCallback.onReceiveValue(null);pendingFileCallback=null;}return;}Uri[] values=null;if(d.getClipData()!=null){int n=d.getClipData().getItemCount();values=new Uri[n];for(int i=0;i<n;i++)values[i]=d.getClipData().getItemAt(i).getUri();}else if(d.getData()!=null)values=new Uri[]{d.getData()};if(values==null||values.length==0)return;ValueCallback<Uri[]> cb=pendingFileCallback;pendingFileCallback=null;if(cb!=null)cb.onReceiveValue(values);pendingUris.clear();for(Uri u:values){takePersistablePermission(u);pendingUris.add(u);}showPendingUriPreview(values[0]);}
    private void takePersistablePermission(Uri u){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}}
    private void showPendingPreview(File f,String side){try{Bitmap b=decodeOriented(f);if(b!=null){deliverPreview(encodePreview(b),side,"DNI / DOCUMENTO");b.recycle();}}catch(Exception e){showError("No se pudo mostrar la vista previa");}}
    private void showPendingUriPreview(Uri u){try{String type=getContentResolver().getType(u),low=String.valueOf(u).toLowerCase(Locale.ROOT);boolean pdf="application/pdf".equalsIgnoreCase(type)||"application/x-pdf".equalsIgnoreCase(type)||low.contains(".pdf");if(pdf){deliverPreview(encodePdfPreview(u),"document","PDF");return;}try(InputStream in=getContentResolver().openInputStream(u)){if(in==null)throw new IOException("open");Bitmap b=BitmapFactory.decodeStream(in);if(b==null)throw new IOException("bitmap");deliverPreview(encodePreview(b),"document","IMAGEN");b.recycle();}}catch(Exception e){showError("No se pudo mostrar la vista previa");}}
    private void processPending(){if(pendingFrontFile!=null){File f=pendingFrontFile;pendingFrontFile=null;processBitmapFile(f,"front");return;}if(pendingReverseFile!=null){File f=pendingReverseFile;pendingReverseFile=null;processBitmapFile(f,"reverse");return;}if(!pendingUris.isEmpty()){List<Uri> items=new ArrayList<>(pendingUris);pendingUris.clear();for(Uri u:items)processUri(u,"document");return;}showError("Añade primero un documento");}
    private void processBitmapFile(File f,String side){try{Bitmap b=decodeOriented(f);if(b==null)throw new IOException("bitmap");runBitmapOcr(b,side,encodePreview(b));}catch(Exception e){showError("No se pudo procesar la imagen");}}
    private Bitmap decodeOriented(File f)throws Exception{Bitmap b=BitmapFactory.decodeFile(f.getAbsolutePath());if(b==null)return null;try{ExifInterface ex=new ExifInterface(f.getAbsolutePath());int o=ex.getAttributeInt(ExifInterface.TAG_ORIENTATION,ExifInterface.ORIENTATION_NORMAL),deg=0;if(o==ExifInterface.ORIENTATION_ROTATE_90)deg=90;else if(o==ExifInterface.ORIENTATION_ROTATE_180)deg=180;else if(o==ExifInterface.ORIENTATION_ROTATE_270)deg=270;if(deg!=0){Matrix m=new Matrix();m.postRotate(deg);Bitmap rr=Bitmap.createBitmap(b,0,0,b.getWidth(),b.getHeight(),m,true);if(rr!=b)b.recycle();b=rr;}}catch(Exception ignored){}return b;}
    private void processUri(Uri u,String side){try{String type=getContentResolver().getType(u),low=String.valueOf(u).toLowerCase(Locale.ROOT);boolean pdf="application/pdf".equalsIgnoreCase(type)||"application/x-pdf".equalsIgnoreCase(type)||low.contains(".pdf");if(pdf){String preview=encodePdfPreview(u);PdfOcrHelper.process(this,u,new PdfOcrHelper.Callback(){public void onSuccess(String text){deliver(parse(text),side,preview);}public void onError(Exception e){deliver(parse(""),side,preview);showError("No se pudo leer el texto del PDF");}});return;}try(InputStream in=getContentResolver().openInputStream(u)){if(in==null)throw new IOException("open");Bitmap b=BitmapFactory.decodeStream(in);if(b==null)throw new IOException("bitmap");runBitmapOcr(b,side,encodePreview(b));}}catch(Exception e){showError("No se pudo procesar el documento");}}
    private void runBitmapOcr(Bitmap b,String side,String preview){try{recognizer.process(InputImage.fromBitmap(b,0)).addOnSuccessListener(x->{deliver(parse(x==null?"":x.getText()),side,preview);if(!b.isRecycled())b.recycle();}).addOnFailureListener(x->{if(!b.isRecycled())b.recycle();showError("No se pudo leer el documento");});}catch(Exception e){if(!b.isRecycled())b.recycle();showError("No se pudo iniciar el OCR");}}
    private String encodePreview(Bitmap b)throws Exception{if(b==null)return"";Bitmap src=b;int max=1400;if(b.getWidth()>max){int h=Math.max(1,(int)((double)b.getHeight()*max/b.getWidth()));src=Bitmap.createScaledBitmap(b,max,h,true);}ByteArrayOutputStream out=new ByteArrayOutputStream();src.compress(Bitmap.CompressFormat.JPEG,82,out);if(src!=b&&!src.isRecycled())src.recycle();return Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);}
    private String encodePdfPreview(Uri u){try(ParcelFileDescriptor pfd=getContentResolver().openFileDescriptor(u,"r")){if(pfd==null)return"";try(android.graphics.pdf.PdfRenderer r=new android.graphics.pdf.PdfRenderer(pfd)){if(r.getPageCount()==0)return"";try(android.graphics.pdf.PdfRenderer.Page p=r.openPage(0)){int w=Math.min(1400,Math.max(900,p.getWidth()*2)),h=Math.max(1,(int)((double)p.getHeight()*w/p.getWidth()));Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);p.render(b,null,null,android.graphics.pdf.PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);String out=encodePreview(b);b.recycle();return out;}}}catch(Exception e){return"";}}
    private void deliverPreview(String preview,String side,String kind){if(preview==null||preview.isEmpty())return;try{JSONObject o=new JSONObject();o.put("side",side==null?"document":side);o.put("preview",preview);o.put("previewOnly",true);o.put("kind",kind==null?"DOCUMENTO":kind);String js="if(window.setOcrResult)window.setOcrResult("+JSONObject.quote(o.toString())+");";runOnUiThread(()->{if(web!=null&&!isFinishing())web.evaluateJavascript(js,null);});}catch(Exception ignored){}}
    private JSONObject parse(String raw){try{String cls=classify(raw);DniOcrParser.Result r=DniOcrParser.parse(raw);JSONObject o=new JSONObject();o.put("documentNumber","Póliza".equals(cls)?"":r.dni);o.put("birthDate","Póliza".equals(cls)?"":normalizeDate(r.birthDate));o.put("name","Póliza".equals(cls)?findPolicyHolder(raw):cleanPersonName(r.name));o.put("surname","Póliza".equals(cls)?"":cleanPersonName(r.surname));o.put("raw",raw==null?"":raw);o.put("policyNumber",findPolicyNumber(raw));o.put("policyType",findPolicyType(raw));o.put("policyExpiry",findPolicyExpiry(raw));o.put("classification",cls);o.put("phone",find(raw,"(?:\\+34\\s*)?[6789]\\d{8}"));o.put("email",find(raw,"[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}"));o.put("address",findLabeled(raw,"DIRECCIÓN","DIRECCION","DOMICILIO","RIESGO"));return o;}catch(Exception e){return new JSONObject();}}
    private String cleanPersonName(String s){if(s==null)return"";String v=s.trim();if(v.matches("(?i).*(IDENTIFICACI[ÓO]N DEL DEUDOR|N[ÚU]MERO DE P[ÓO]LIZA|TOMADOR|CONDICIONES PARTICULARES).*"))return"";return v;}
    private String normalizeDate(String s){if(s==null)return"";String v=s.trim().replace('.','/').replace('-','/');Matcher m=Pattern.compile("^(\\d{1,2})[\\/](\\d{1,2})[\\/](\\d{4})$").matcher(v);if(m.matches())return String.format(Locale.ROOT,"%02d/%02d/%s",Integer.parseInt(m.group(1)),Integer.parseInt(m.group(2)),m.group(3));String n=v.replaceAll("\\D","");if(n.length()==8){int d=Integer.parseInt(n.substring(0,2)),mo=Integer.parseInt(n.substring(2,4));if(d>=1&&d<=31&&mo>=1&&mo<=12)return n.substring(0,2)+"/"+n.substring(2,4)+"/"+n.substring(4);}return v;}
    private String classify(String raw){String u=(raw==null?"":raw).toUpperCase(Locale.ROOT);boolean pol=u.contains("PÓLIZA")||u.contains("POLIZA")||u.contains("TOMADOR")||u.contains("ASEGURADO")||u.contains("FECHA DE EFECTO")||u.contains("CONDICIONES PARTICULARES")||u.contains("OCASO HOGAR");if(pol)return"Póliza";boolean dni=u.contains("DNI")||u.contains("NIE")||u.contains("IDESP")||u.matches("(?s).*\\b[XYZ]?[0-9]{7}[A-Z]\\b.*");return dni?"DNI/NIE":"Documento";}
    private String findPolicyHolder(String raw){if(raw==null)return"";Matcher m=Pattern.compile("(?im)TOMADOR(?:\\s+DEL\\s+SEGURO)?\\s*[:\\-]?\\s*([^\\r\\n]+)").matcher(raw);if(m.find())return cleanPersonName(m.group(1));return"";}
    private String findPolicyNumber(String raw){if(raw==null)return"";Matcher m=Pattern.compile("(?i)(?:N[º°O]\\s*)?(?:NÚMERO DE P[ÓO]LIZA|NUMERO DE POLIZA|P[ÓO]LIZA|POLIZA)\\s*[:#-]?\\s*([A-Z0-9./_-]{4,})").matcher(raw);return m.find()?m.group(1).trim():"";}
    private String findPolicyExpiry(String raw){if(raw==null)return"";String[] labels={"FECHA DE VENCIMIENTO","VENCIMIENTO","FECHA FIN","FIN DE SEGURO","CADUCIDAD"};for(String label:labels){Matcher m=Pattern.compile("(?im)"+Pattern.quote(label)+"\\s*[:#-]?\\s*([^\\r\\n]+)").matcher(raw);if(m.find()){Matcher d=Pattern.compile("\\d{1,2}\\s*[ /.-]\\s*\\d{1,2}\\s*[ /.-]\\s*\\d{4}").matcher(m.group(1));if(d.find())return normalizeDate(d.group());}}return"";}
    private String findPolicyType(String raw){String u=(raw==null?"":raw).toUpperCase(Locale.ROOT);if(u.contains("DECESOS"))return"Decesos";if(u.contains("COMUNIDAD"))return"Comunidades";if(u.contains("HOGAR"))return"Hogar";if(u.contains("AUTO")||u.contains("AUTOMOVIL")||u.contains("AUTOMÓVIL"))return"Auto";if(u.contains("VIDA"))return"Vida";return"Póliza";}
    private String findLabeled(String raw,String...labels){if(raw==null)return"";for(String line:raw.split("\\R")){String u=line.toUpperCase(Locale.ROOT);for(String label:labels){int p=u.indexOf(label);if(p>=0){String v=line.substring(Math.min(line.length(),p+label.length())).replaceFirst("^[\\s:.-]+","").trim();if(!v.isEmpty())return v;}}}return"";}
    private String find(String raw,String regex){if(raw==null)return"";Matcher m=Pattern.compile(regex,Pattern.CASE_INSENSITIVE).matcher(raw);return m.find()?m.group():"";}
    private void deliver(JSONObject o,String side,String preview){try{String effectiveSide=side;if("document".equals(side)&&"DNI/NIE".equals(o.optString("classification","")))effectiveSide="front";o.put("side",effectiveSide==null?"document":effectiveSide);o.put("preview",preview==null?"":preview);o.put("previewOnly",false);if("front".equals(effectiveSide)){frontRaw=o.optString("raw","");frontParsed=o;}if("reverse".equals(effectiveSide)){reverseRaw=o.optString("raw","");reverseParsed=o;}JSONObject merged=new JSONObject();JSONObject base=frontParsed.length()>0?frontParsed:o;JSONObject rev=reverseParsed.length()>0?reverseParsed:null;String[] keys={"documentNumber","name","surname","birthDate","policyNumber","policyType","policyExpiry","phone","email","address","classification","raw"};for(String k:keys){String val=base.optString(k,"");if(val.isEmpty()&&rev!=null)val=rev.optString(k,"");merged.put(k,val);}merged.put("side",effectiveSide==null?"document":effectiveSide);merged.put("preview",preview==null?"":preview);merged.put("previewOnly",false);merged.put("frontRead",!frontRaw.isEmpty());merged.put("reverseRead",!reverseRaw.isEmpty());String js="if(window.setOcrResult)window.setOcrResult("+JSONObject.quote(merged.toString())+");";runOnUiThread(()->{if(web!=null&&!isFinishing())web.evaluateJavascript(js,null);});}catch(Exception e){showError("No se pudo mostrar el resultado OCR");}}
    private void clearPending(){pendingFrontFile=null;pendingReverseFile=null;pendingUris.clear();frontRaw="";reverseRaw="";frontParsed=new JSONObject();reverseParsed=new JSONObject();String js="if(window.clearOcrUi)window.clearOcrUi();";runOnUiThread(()->{if(web!=null&&!isFinishing())web.evaluateJavascript(js,null);});}
    private void showError(String m){runOnUiThread(()->Toast.makeText(this,m,Toast.LENGTH_LONG).show());}
    @Override protected void onDestroy(){if(pendingFileCallback!=null){pendingFileCallback.onReceiveValue(null);pendingFileCallback=null;}if(recognizer!=null)recognizer.close();if(web!=null)web.destroy();super.onDestroy();}
}
