from pathlib import Path
import re

JAVA = Path('app/src/main/java/com/rgapro1/ocaso/MainActivity.java')
s = JAVA.read_text(encoding='utf-8')
lines = s.splitlines()
changed = False

fixed_array = 'String[] lines=(raw==null?"":raw.replace("\\r","\\n")).split("\\n");'
fixed_text = "String text=raw==null?\"\":raw.replace('\\r','\\n');"


def normalize_java_escapes(line):
    """Remove accidental Markdown-style backslash escapes without breaking regex dots."""
    out = []
    i = 0
    in_string = False
    in_char = False
    escaped = False
    while i < len(line):
        c = line[i]
        if escaped:
            out.append(c)
            escaped = False
            i += 1
            continue
        if c == '\\':
            j = i
            while j < len(line) and line[j] == '\\':
                j += 1
            run = line[i:j]
            nxt = line[j] if j < len(line) else ''
            # Outside literals, a backslash before Java punctuation is always malformed.
            # Inside literals, Markdown-style escapes such as \\_ are malformed too,
            # but \\. is commonly a legitimate regex escape and must be preserved.
            punctuation = ':<>_%.,'
            if nxt in punctuation and (nxt != '.' or not in_string):
                out.append(nxt)
                i = j + 1
                continue
            out.append(run)
            i = j
            continue
        out.append(c)
        if c == '"' and not in_char:
            in_string = not in_string
        elif c == "'" and not in_string:
            in_char = not in_char
        i += 1
    return ''.join(out)


for i, line in enumerate(lines):
    indent = line[:len(line) - len(line.lstrip())]
    stripped = line.strip()

    # Normalize malformed punctuation escapes generated by previous patch passes.
    normalized = normalize_java_escapes(line)
    if normalized != line:
        lines[i] = normalized
        line = normalized
        stripped = line.strip()
        indent = line[:len(line) - len(line.lstrip())]
        changed = True

    if 'String[] lines=' in line and 'raw' in line and 'replace' in line and '.split' in line:
        if lines[i] != indent + fixed_array:
            lines[i] = indent + fixed_array
            changed = True
    elif re.search(r'String\s+text\s*=\s*raw\s*==\s*null', stripped) and 'raw' in line and 'replace' in line:
        if lines[i] != indent + fixed_text:
            lines[i] = indent + fixed_text
            changed = True

if changed:
    JAVA.write_text('\n'.join(lines) + ('\n' if s.endswith('\n') else ''), encoding='utf-8')
    print('Malformed Java raw-line and escaped-punctuation normalization fixed')
else:
    print('No malformed Java raw-line normalization found')
