from pathlib import Path
import re

JAVA = Path('app/src/main/java/com/rgapro1/ocaso/MainActivity.java')
s = JAVA.read_text(encoding='utf-8')
lines = s.splitlines()
changed = False

# Canonical Java source forms. These Python strings must produce exactly
# these Java literals in MainActivity.java: "\\r" and "\\n".
FIXED_ARRAY = 'String[] lines=(raw==null?"":raw.replace("\\\\r","\\\\n")).split("\\\\n");'
FIXED_TEXT = 'String text=raw==null?"":raw.replace("\\\\r","\\\\n");'


def repair_generated_line(line):
    """Return a canonical declaration when a patch generated a malformed one."""
    indent = line[:len(line) - len(line.lstrip())]

    # These declarations are generated by several patch scripts. Once they
    # are detected, replace the complete declaration instead of trying to
    # repair individual backslashes. This makes repeated workflow runs
    # idempotent and prevents Markdown/Python escaping from leaking into Java.
    if re.search(r'String\s*\[\]\s*lines\s*=.*raw', line):
        return indent + FIXED_ARRAY
    if re.search(r'String\s+text\s*=.*raw', line):
        return indent + FIXED_TEXT

    # Remove accidental Markdown punctuation escaping, but preserve genuine
    # Java escapes such as \n, \r and escaped quotes.
    normalized = (line.replace('\\:', ':')
                       .replace('\\<', '<')
                       .replace('\\>', '>')
                       .replace('\\_', '_')
                       .replace('\\%', '%'))
    normalized = re.sub(r'(?<!\\)\\\.', '.', normalized)
    return normalized


for i, original in enumerate(lines):
    line = repair_generated_line(original)
    if line != original:
        lines[i] = line
        changed = True

# Final deterministic pass over the complete source. This catches malformed
# declarations even when an earlier patch inserted extra backslashes around
# punctuation or character literals before this script runs.
out = []
for line in lines:
    repaired = repair_generated_line(line)
    if repaired != line:
        changed = True
    out.append(repaired)

result = '\n'.join(out) + ('\n' if s.endswith('\n') else '')
if result != s:
    JAVA.write_text(result, encoding='utf-8')
    changed = True

if changed:
    print('Malformed Java raw-line, escaped-punctuation, and generated newline normalization fixed')
else:
    print('No malformed Java raw-line normalization found')
