from pathlib import Path
import re

JAVA = Path('app/src/main/java/com/rgapro1/ocaso/MainActivity.java')
s = JAVA.read_text(encoding='utf-8')
lines = s.splitlines()
changed = False

# Build Java escapes from chr(92) so this Python script cannot accidentally
# turn them into real CR/LF characters or over-escape them.
BS = chr(92)
FIXED_ARRAY = 'String[] lines=(raw==null?"":raw.replace("' + BS + 'r","' + BS + 'n")).split("' + BS + 'n");'
FIXED_TEXT = 'String text=raw==null?"":raw.replace("' + BS + 'r","' + BS + 'n");'


def repair_generated_line(line):
    """Return a canonical Java line and remove accidental punctuation escapes."""
    indent = line[:len(line) - len(line.lstrip())]

    # These declarations are generated by several patch scripts. Replace the
    # complete declaration instead of attempting incremental backslash fixes.
    if re.search(r'String\s*\[\]\s*lines\s*=.*raw', line):
        return indent + FIXED_ARRAY
    if re.search(r'String\s+text\s*=.*raw', line):
        return indent + FIXED_TEXT

    # Patch scripts can repeatedly escape punctuation. In Java source these
    # backslashes are invalid (for example row\.setPadding and idx\<z.length()).
    # Remove every consecutive backslash immediately before punctuation that
    # is never a Java escape. Keep valid escapes such as \n, \r, \t, \" and \'.
    normalized = line
    for punctuation in '.:<>_%':
        normalized = re.sub(
            r'\\+' + re.escape(punctuation),
            punctuation,
            normalized,
        )
    return normalized


out = []
for original in lines:
    repaired = repair_generated_line(original)
    if repaired != original:
        changed = True
    out.append(repaired)

result = '\n'.join(out) + ('\n' if s.endswith('\n') else '')
if result != s:
    JAVA.write_text(result, encoding='utf-8')
    changed = True

# Fail the workflow instead of allowing javac to report a misleading error if
# a later generator ever reintroduces these malformed punctuation escapes.
remaining = []
for number, line in enumerate(out, 1):
    if re.search(r'\\+[.:<>_%]', line):
        remaining.append(number)
if remaining:
    raise SystemExit(
        'Malformed Java punctuation escapes remain in MainActivity.java at lines: '
        + ', '.join(map(str, remaining))
    )

if changed:
    print('Malformed Java raw-line, repeated escaped-punctuation, and generated newline normalization fixed')
else:
    print('No malformed Java raw-line normalization found')
