from pathlib import Path
import re

# Product-aware native OCR parser
p=Path('app/src/main/java/com/rgapro1/ocaso/RgaProActivity.java')
s=p.read_text(encoding='utf-8')
pat=r'private JSONObject parse\(String raw\)throws Exception\{.*?\n    \}\n    private String findPolicyNumber'
if re.search(pat,s,re.S):
    s=re.sub(pat,'private JSONObject parse(String raw)throws Exception{return PolicyOcrParser.parse(raw);}\n    private String findPolicyNumber',s,flags=re.S)
p.write_text(s,encoding='utf-8')

# Adaptive launcher icon using the existing RGA Pro vector.
man=Path('app/src/main/AndroidManifest.xml')
m=man.read_text(encoding='utf-8').replace('android:icon="@drawable/ic_rgapro" android:roundIcon="@drawable/ic_rgapro"','android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher"')
man.write_text(m,encoding='utf-8')
res=Path('app/src/main/res');(res/'mipmap-anydpi-v26').mkdir(parents=True,exist_ok=True);(res/'mipmap').mkdir(parents=True,exist_ok=True)
(res/'mipmap-anydpi-v26/ic_launcher.xml').write_text('''<?xml version="1.0" encoding="utf-8"?><adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android"><background android:drawable="@color/ic_launcher_bg"/><foreground android:drawable="@drawable/ic_rgapro"/></adaptive-icon>''',encoding='utf-8')
(res/'mipmap/ic_launcher.xml').write_text('''<?xml version="1.0" encoding="utf-8"?><vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108"><path android:fillColor="#071B3A" android:pathData="M0,0h108v108h-108z"/><path android:fillColor="#0B1F45" android:pathData="M12,4L96,4Q104,4 104,12L104,66Q104,91 54,104Q4,91 4,66L4,12Q4,4 12,4Z"/><path android:fillColor="#1199F4" android:pathData="M10,18V11Q10,8 13,8H95Q98,8 98,11V18H93V13H15V18Z"/><path android:fillColor="#FFFFFF" android:pathData="M16,31h19q7,0 7,7 0,6 -6,8l7,9h-9l-7,-8h-3v8h-8zM24,37v5h9q2,0 2,-3 0,-2 -2,-2z"/><path android:fillColor="#FFFFFF" android:pathData="M44,31h17q8,0 8,8v8q0,8 -8,8H44zM52,37v12h8q1,0 1,-2v-8q0,-2 -1,-2z"/><path android:fillColor="#1098F4" android:pathData="M68,31h20v6H76v4h9v6h-9v8h-8z"/><path android:fillColor="#16A8F8" android:pathData="M22,60h64v3H22z"/><path android:fillColor="#0B9CF5" android:pathData="M29,68h11q6,0 6,6t-6,6h-5v7h-6zM35,73v3h4q1,0 1,-1.5T39,73z"/><path android:fillColor="#0B9CF5" android:pathData="M48,68h12q6,0 6,6 0,4 -4,5l5,8h-7l-4,-7h-2v7h-6zM54,73v3h5q1,0 1,-1.5T59,73z"/><path android:fillColor="#0B9CF5" android:pathData="M69,68h11q6,0 6,6v7q0,6 -6,6H69zM75,73v9h4q1,0 1,-2v-5q0,-2 -1,-2z"/><path android:fillColor="#FFFFFF" android:pathData="M54,90Q54,84 60,84T66,90V96Q66,102 60,104Q54,102 54,96Z"/><path android:fillColor="#0B8FF2" android:pathData="M58,94l2,2 4,-5 2,2 -6,7 -4,-4z"/></vector>''',encoding='utf-8')
(res/'values/ic_launcher_colors.xml').write_text('<?xml version="1.0" encoding="utf-8"?><resources><color name="ic_launcher_bg">#071B3A</color></resources>',encoding='utf-8')

# Web UI: explicit login, automatic document classification, product-specific fields and automatic matching.
h=Path('app/src/main/assets/prototype/index_v3.html');s=h.read_text(encoding='utf-8')
s=s.replace('body{margin:0;font-family:Inter,system-ui', 'body{margin:0;font-family:Inter,system-ui')
s=s.replace('.app{max-width:760px;', '.app{max-width:760px;')
s=s.replace('</style></head><body><div class="app">','''#auth{position:fixed;inset:0;z-index:9999;background:linear-gradient(135deg,#071b3a,#0b3f8d);display:flex;align-items:center;justify-content:center;padding:18px}body.auth-ok #auth{display:none}body:not(.auth-ok) .app{display:none}.auth-card{width:min(460px,100%);background:#071b3acc;border:1px solid #ffffff33;border-radius:24px;padding:22px;color:#fff;box-shadow:0 20px 60px #0006}.auth-logo{width:130px;height:130px;display:block;margin:0 auto 8px;border-radius:28px}.auth-title{text-align:center;font-size:30px;font-weight:900}.auth-sub{text-align:center;color:#bfd0e8;margin-bottom:18px}.auth-card input{width:100%;padding:14px;margin:7px 0;border-radius:13px;border:1px solid #ffffff33;background:#061633;color:#fff}.auth-card button{width:100%;margin-top:8px}.auth-link{background:transparent!important;color:#66b8ff;border:1px solid #168cff!important}.auth-note{font-size:12px;color:#b9c9df;text-align:center;margin-top:10px}</style></head><body><div id="auth"><div class="auth-card"><img class="auth-logo" alt="RGA PRO" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 108 108'%3E%3Crect width='108' height='108' rx='24' fill='%23071b3a'/%3E%3Cpath d='M10 18V11Q10 8 13 8H95Q98 8 98 11V18' fill='none' stroke='%231199f4' stroke-width='5'/%3E%3Cpath d='M12 20Q12 13 19 13H89Q96 13 96 20V66Q96 89 54 101Q12 89 12 66Z' fill='%230b1f45' stroke='%231198f4' stroke-width='4'/%3E%3Ctext x='54' y='52' fill='white' font-size='24' font-family='Arial' font-weight='900' text-anchor='middle'%3ERGA%3C/text%3E%3Cpath d='M22 61H86' stroke='%23119cf4' stroke-width='3'/%3E%3Ctext x='54' y='80' fill='%23119cf4' font-size='17' font-family='Arial' font-weight='900' text-anchor='middle'%3EPRO%3C/text%3E%3Cpath d='M44 91Q44 84 51 84Q54 84 57 88Q60 84 63 84Q70 84 70 91V97Q54 103 44 97Z' fill='white'/%3E%3Cpath d='M52 94l3 3 7-8' fill='none' stroke='%230b78e8' stroke-width='3'/%3E%3C/svg%3E"><div class="auth-title">Bienvenido a RgaPro</div><div class="auth-sub">Clientes, pólizas y documentos</div><input id="authUser" placeholder="Usuario"><input id="authPin" type="password" inputmode="numeric" maxlength="6" placeholder="PIN de 6 dígitos"><button class="primary" onclick="loginUser()">Entrar</button><button class="auth-link" onclick="newUser()">＋ Nuevo usuario</button><div class="auth-note">Los usuarios y datos se guardan localmente en este dispositivo.</div></div></div><div class="app">''')
# Auto mode and clearer input labels.
s=s.replace("ocrType='DNI'","ocrType='AUTO'")
s=s.replace("<button id=\"ocrTypeDni\" class=\"primary\" onclick=\"setOcrType('DNI')\">DNI / NIE</button><button id=\"ocrTypeDoc\" class=\"secondary\" onclick=\"setOcrType('DOCUMENTO')\">Documento</button><button id=\"ocrTypePol\" class=\"secondary\" onclick=\"setOcrType('POLIZA')\">Póliza</button>","<button id=\"ocrTypeAuto\" class=\"primary\" onclick=\"setOcrType('AUTO')\">🔎 Detectar automáticamente</button><button id=\"ocrTypeDni\" class=\"secondary\" onclick=\"setOcrType('DNI')\">🪪 DNI / NIE</button><button id=\"ocrTypePol\" class=\"secondary\" onclick=\"setOcrType('POLIZA')\">📄 Póliza</button>")
s=s.replace('📷 Tomar anverso','📷 Tomar fotografía').replace('📁 Foto / PDF','📁 Cargar PDF / JPG')
# Automatic classifier in native result callback.
s=s.replace("window.setOcrResult=function(json){try{let x=JSON.parse(json);ocrData={...ocrData,...x};", "window.setOcrResult=function(json){try{let x=JSON.parse(json);ocrData={...ocrData,...x};if(ocrType==='AUTO'){let raw=norm(x.raw||'');ocrType=(x.policyNumber||x.policyType||/\\b(TOMADOR|P[ÓO]LIZA|CONDICIONES PARTICULARES|FECHA DE EFECTO|ASEGURADO)\\b/.test(raw))?'POLIZA':((x.documentNumber||/\\b(DNI|NIE|IDESP)\\b/.test(raw))?'DNI':'DOCUMENTO');}")
# Product-specific rendering.
old=r"function renderOcrFields\(\)\{.*?\nfunction field"
m=re.search(old,s,re.S)
if m:
    repl="""function renderOcrFields(){let b=document.getElementById('ocrFields');if(ocrType==='DNI')b.innerHTML=field('DNI / NIE','documentNumber',ocrData.documentNumber)+field('NOMBRE','name',ocrData.name)+field('APELLIDOS','surname',ocrData.surname)+field('FECHA DE NACIMIENTO','birthDate',ocrData.birthDate)+field('DIRECCIÓN','address',ocrData.address)+field('TELÉFONO','phone',ocrData.phone)+field('EMAIL','email',ocrData.email);else if(ocrType==='POLIZA'){let t=norm(ocrData.policyType),z=field('Nº PÓLIZA','policyNumber',ocrData.policyNumber)+field('PRODUCTO','policyType',ocrData.policyType)+field('NOMBRE Y APELLIDOS','holder',ocrData.holder)+field('DNI/NIE','documentNumber',ocrData.documentNumber)+field('FECHA DE EMISIÓN / EFECTO','effectiveDate',ocrData.effectiveDate||ocrData.issueDate)+field('VENCIMIENTO','policyExpiry',ocrData.policyExpiry);if(t.includes('vida')||t.includes('ahorro'))z+=field('PRIMAS','premiums',ocrData.premiums);if(t.includes('deces'))z+='<div class=\"info\">Decesos: los asegurados se vincularán automáticamente con personas existentes por DNI/NIE y, si no existe, por coincidencia única de nombre. El tomador que también sea asegurado no se duplica.</div>';b.innerHTML=z+'<div class=\"notice\">Solo se guardan los campos necesarios para el producto identificado. Se conserva el documento original.</div>'}else b.innerHTML=field('Nº DOCUMENTO','documentNumber',ocrData.documentNumber)+field('NOMBRE','name',ocrData.name)+field('APELLIDOS','surname',ocrData.surname)+field('CLASIFICACIÓN','policyType',ocrData.policyType)}
function field"""
    s=s[:m.start()]+repl+s[m.end():]
# Replace saveOcr with automatic relation logic.
old=r"async function saveOcr\(\)\{.*?\nfunction extractInsureds"
m=re.search(old,s,re.S)
if m:
    repl="""async function saveOcr(){readOcr();if(ocrType==='AUTO')return alert('Clasificación pendiente: vuelve a leer el documento.');if(ocrType==='DNI'){if(!ocrData.documentNumber||!ocrData.name||!ocrData.surname){alert('Faltan datos esenciales del DNI/NIE.');return}let c=state.clients.find(x=>norm(x.dni)===norm(ocrData.documentNumber));let v={name:ocrData.name,surname:ocrData.surname,dni:ocrData.documentNumber,birthDate:ocrData.birthDate||'',phone:ocrData.phone||'',email:ocrData.email||'',address:ocrData.address||''};if(c)Object.assign(c,v);else{c={id:uid('c'),...v};state.clients.push(c)}let d=await persistSource('DNI/NIE');c.documentIds=c.documentIds||[];if(d)c.documentIds.push(d.id);saveState();clearOcr();show('clients');return}if(ocrType==='POLIZA'){let holder=ocrData.holder||'',hc=ocrData.documentNumber?state.clients.find(c=>norm(c.dni)===norm(ocrData.documentNumber)):null;if(!hc&&holder)hc=state.clients.find(c=>norm(fullName(c))===norm(holder));let d=await persistSource('Póliza');let ins=extractInsureds(ocrData.raw||'',ocrData);let p={id:uid('p'),number:ocrData.policyNumber||'SIN-NUMERO',type:ocrData.policyType||'Póliza',holder,holderClientId:hc?.id||null,clientIds:hc?[hc.id]:[],expiryDate:ocrData.policyExpiry||'',effectiveDate:ocrData.effectiveDate||ocrData.issueDate||'',premiums:ocrData.premiums||'',insureds:ins,documentId:d?.id||null,raw:ocrData.raw||'',createdAt:Date.now()};if(norm(p.type).includes('deces'))p.insureds.forEach(x=>{let c=x.dni?state.clients.find(c=>norm(c.dni)===norm(x.dni)):null;if(!c){let nm=norm((x.name||'')+' '+(x.surname||''));let cc=state.clients.filter(c=>norm(fullName(c))===nm);c=cc.length===1?cc[0]:null}if(c){x.clientId=c.id;p.clientIds.push(c.id)}});p.clientIds=[...new Set(p.clientIds)];state.policies.push(p);saveState();clearOcr();openPolicy(p.id);return}alert('Documento no clasificado: no se guarda como póliza.')}\nfunction extractInsureds"""
    s=s[:m.start()]+repl+s[m.end():]
# Add login functions before final initialization.
anchor="(function migrate(){"
login="""function authUsers(){try{return JSON.parse(localStorage.getItem('rgapro_users')||'[]')}catch(e){return[]}}function loginUser(){let u=document.getElementById('authUser').value.trim(),p=document.getElementById('authPin').value.trim(),ok=authUsers().find(x=>x.user===u&&x.pin===p);if(!ok){alert('Usuario o PIN incorrectos.');return}localStorage.setItem('rgapro_session',u);document.body.classList.add('auth-ok')}function newUser(){let u=prompt('Nuevo usuario');if(!u)return;let p=prompt('PIN de 6 dígitos');if(!/^\\d{6}$/.test(p||'')){alert('El PIN debe tener 6 dígitos.');return}let a=authUsers();if(a.some(x=>x.user.toLowerCase()===u.toLowerCase())){alert('Ese usuario ya existe.');return}a.push({user:u,pin:p});localStorage.setItem('rgapro_users',JSON.stringify(a));document.getElementById('authUser').value=u;document.getElementById('authPin').value=p;loginUser()}if(localStorage.getItem('rgapro_session'))document.body.classList.add('auth-ok');"""
s=s.replace(anchor,login+anchor,1)
h.write_text(s,encoding='utf-8')
print('final patch applied')
